#encoding=utf-8
zh_cn={
    "lang":"zh-cn",
    "start":"启动。",
    "parent_process":"父进程",
    "parent_begin":"启动，版本：{version}，配置：\n",
    "all_is_fine":"运行正常。",
    "increase_priority":"尝试提高进程优先级，命令返回：\n",
    "write_hosts":"尝试修改hosts......",
    "access_denied":"拒绝访问",
    "no_access":"权限不足。",
    "delete_log":"删除了{file_path} 因为{window_title}({window_class})违反：{rule_title}({rule_class})",
    "close_log":"关闭了{window_title}({window_class}) 因为违反：{rule_title}({rule_class})",
    "keyword_log":"关闭了{window_title}({window_class}) 因为触发关键词：{keyword}",
    "illegal_program":"已禁止违规程序",
    "illegal_window":"已禁止违规窗口",
    "closed":"已关闭",
    "closed_and_deleted":"已关闭并删除",
    "trigger_keyword":"触发关键词“{keyword}”",
    "suspend":"紧急暂停了webblock",
    "suspend_title":"紧急暂停",
    "suspend_content":"紧急暂停了webblock功能，持续{time}。",
    "suspend_wrong_password":"检测到紧急暂停标识文件，但密码不匹配。",
    "not_found":"未找到{obj}。",
    "ssm_tip":"如需将截屏移动到桌面，请将文件重命名，使之不以“截屏文件”开头",
    "lightframe_window_missing":"timeout:已等待{wait_time}秒，时间/日历窗口还未启动。",
    "lightframe_is_not_running":"lightframe并未运行，请检查自启动。",
    "lightframe_is_running":"lightframe正在运行，请检查是否设置了时间和日历组件。",
    "listening_start":"开始监听。",
    "new_loop":"新循环",
    "time_window_missing":"时间窗口未找到！重启窗口...",
    "calendar_window_missing":"日历窗口未找到！重启窗口...",
    "check_if_success":"检测是否成功...",
    "time_window_restart_failed":"时间窗口未重启成功，检查是否设置了时间窗口。",
    "calendar_window_restart_failed":"日历窗口未重启成功，检查是否设置了日历窗口。",
    "checking_end":"检测完成",
    "file_move":"移动了文件：{file}。",
    "screenshots_sorted":"截屏文件已整理",
    "toast_move_file":"{file0}已移动到“截图”文件夹。",
    "toast_move_files":"{file0}等{num}个文件已移动到“截图”文件夹。",
    "process_dc_end":"rslr和ssm都停止了工作，子进程desktop_control结束。",
    "log_overflow":"日志溢出{num}条，已删除。",
    "close_window":"关闭窗口：",
    "same":"同上",
    "time_use":" 用时 ",
    "illegal_time":"不正常的时间",
    "colon":"：",
    "or":"或",
    "toast_illegal_time":"当前时间在规定开机时间{allowed_time_start}之前，或{allowed_time_end}之后，将在10秒后自动关机。",
    "auto_updated":"已更新至最新版本",
    "toast_auto_updated":"新版本{version}已生效，点击可查看更新日志。",
    "error_illegal_package":"返回的内容不正常",
    "error_check_update":"检查更新时出错",
    "retry":"，重新尝试...{times}/3次",
    "latest_version":"版本已是最新！",
    "no_download_url":"有最新版本：{latest_version}，但无下载链接，请稍后重试。",
    "start_download":"有最新版本：{latest_version}，开始下载更新包......",
    "download_url":"下载地址：",
    "error_download":"下载更新包时出错",
    "unpacking":"更新包下载完成，开始解压.......",
    "add_self_starting":"解压完成，添加自启动...",
    "prepared":"更新已准备完成，等待重启...",
    "icon_missing":"警告：D:/tools/icon.ico不存在，通知的图标无法正常显示！",
    "call_toast":"发送了通知\n标题：{title}\n内容：{content}\n命令：{command}",
    "toast_title_default":"schoolpctool通知",
    "error_toasting":"发送通知时出错",
    "explorer_crashing":"估计是explorer.exe崩溃导致的错误，此版本无法解决。",
    "hour":"小时",
    "minute":"分钟",
    "second":"秒",
}
en={
    "lang":"en",
    "start":"start.",
    "parent_process":"parent process",
    "parent_begin":"start,version:{version},config:\n",
    "all_is_fine":"All is fine.",
    "increase_priority":"trying to increase process priority with a command, which returns:\n",
    "write_hosts":"trying to write hosts......",
    "access_denied":"access denied",
    "no_access":"No access.",
    "delete_log": "deleted {file_path} because {window_title} ({window_class}) violated: {rule_title} ({rule_class})",
    "close_log": "Closed {window_title} ({window_class}) due to violation of: {rule_title} ({rule_class})",
    "keyword_log": "{window_title} ({window_class}) was closed due to triggering keyword: {keyword}",
    "illegal_program": "Illegal program prohibited",
    "illegal_window": "Illegal window has been banned",
    "closed": "Closed",
    "closed_and_deleted": "Closed and deleted",
    "trigger_keyword": 'triggers keyword" {keyword} "',
    "suspend":"urgently paused webblock function.",
    "suspend_title": "Emergency pause",
    "suspend_content": "The webblock function has been urgently paused for {time}.",
    "suspend_wrong_password": "An emergency pause identification file was detected, but the password does not match.",
    "not_found": "{obj} is not found.",
    "ssm_tip": "To move a screenshot to the desktop, please rename the file so that it does not start with “截屏文件”",
    "lightframe_window_missing": "timeout: Waiting for {wait_time} seconds, the time/calendar window has not yet started.",
    "lightframe_is_not_running":"Lightframe is not running, please check for self startup.",
    "lightframe_is_running":"Lightframe is running. Please check if the time and calendar components are set.",
    "listening_start": "Start listening.",
    "new_loop": "New loop",
    "time_window_missing": "Time window not found! Restart window...",
    "calendar_window_missing": "Calendar window not found! Restart window...",
    "check_if_success": "Check if successful...",
    "time_window_restart_failed": "The time window did not restart successfully. Check if the time window has been set.",
    "calendar_window_restart_failed": "The calendar window did not restart successfully. Check if the calendar window has been set.",
    "checking_end": "Detection completed",
    "file_move": "Moved file: {file}.",
    "screenshots_sorted": "Screenshots files organized",
    "toast_move_file": "{file0} has been moved to the screenshots folder.",
    "toast_move_files": "{num} files such as {file0} have been moved to the Screenshots folder.",
    "process_dc_end": "Both rslr and ssm have stopped working, and the child process desktop_control has ended.",
    "log_overflow": "Log overflow {num} entries, deleted.",
    "close_window": "Close window:",
    "same": "Same as above",
    "time_use": " with time using ",
    "illegal_time": "Abnormal time",
    "colon":":",
    "or": " or ",
    "toast_illegal_time": "If the current time is before the specified startup time {allowed_timestart} or after {allowed_timeend}, it will automatically shut down after 10 seconds.",
    "auto_updated": "Updated to the latest version",
    "toast_auto_updated": "The new version {version} has taken effect. Click to view the update log.",
    "error_illegal_package": "The returned content is abnormal",
    "error_check_update": "Error checking for updates",
    "retry": "Try again... {times}/3 times",
    "latest_version": "The version is already the latest!",
    "no_download_url": "The latest version is available: {latest_version}, but there is no download link. Please try again later.",
    "start_download": "There is the latest version: {latest_version}, start downloading the update package...",
    "download_url": "Download address:",
    "error_download": "Error downloading update package",
    "unpacking": "The download of the update package is complete, and decompression is starting...",
    "add_self_starting": "Decompression completed, add self starting...",
    "prepared": "The update is ready to complete, waiting for restart...",
    "icon_missing": "Warning: D:/tools/icon.ico does not exist, notification icon cannot be displayed properly!",
    "call_toast": "Notification sent \n Title: {title} \n Content: {content} \n Command: {command}",
    "toast_title_default": "schoolpctool notification",
    "error_toasting": "Error sending notification",
    "explorer_crashing": "It is estimated that the error was caused by the crash of explorer.exe, and this version cannot resolve it.",
    "hour":" hour(s) ",
    "minute":" minute(s) ",
    "second":" second(s) ",
}
jp = {
"lang": "jp",
"start": "起動します。",
"parent_process": "親プロセス",
"parent_begin": "起動、バージョン：{version}、設定：\n",
"all_is_fine": "正常に実行されています。",
"increase_priority": "プロセスの優先度を上げようとしています、コマンドの戻り値：\n",
"write_hosts": "hostsファイルを変更しようとしています...",
"access_denied": "アクセスが拒否されました",
"no_access": "アクセス権がありません。",
"delete_log": "{file_path}を削除しました、理由：{window_title}({window_class})が違反しました：{rule_title}({rule_class})",
"close_log": "{window_title}({window_class})を閉じました、理由：{rule_title}({rule_class})に違反しました",
"keyword_log": "{window_title}({window_class})を閉じました、キーワードがトリガーされました：{keyword}",
"illegal_program": "違法なプログラムが禁止されました",
"illegal_window": "違法なウィンドウが禁止されました",
"closed": "閉じられました",
"closed_and_deleted": "閉じられて削除されました",
"trigger_keyword": "キーワード「{keyword}」がトリガーされました",
"suspend": "webblockを緊急停止しました",
"suspend_title": "緊急停止",
"suspend_content": "webblock機能を緊急停止しました、{time}継続します。",
"suspend_wrong_password": "緊急停止フラグファイルが検出されましたが、パスワードが一致しません。",
"not_found": "{obj}が見つかりません。",
"ssm_tip": "スクリーンショットをデスクトップに移動するには、ファイル名を「スクリーンショットファイル」で始まらないように変更してください",
"lightframe_window_missing": "タイムアウト：{wait_time}秒待機しましたが、時間/カレンダーウィンドウがまだ起動していません。",
"lightframe_is_not_running": "lightframeは実行されていません、自動起動を確認してください。",
"lightframe_is_running": "lightframeが実行中です、時間とカレンダーコンポーネントが設定されているか確認してください。",
"listening_start": "監視を開始します。",
"new_loop": "新しいループ",
"time_window_missing": "時間ウィンドウが見つかりません！ウィンドウを再起動しています...",
"calendar_window_missing": "カレンダーウィンドウが見つかりません！ウィンドウを再起動しています...",
"check_if_success": "成功したかどうかを確認しています...",
"time_window_restart_failed": "時間ウィンドウを再起動できませんでした、時間ウィンドウが設定されているか確認してください。",
"calendar_window_restart_failed": "カレンダーウィンドウを再起動できませんでした、カレンダーウィンドウが設定されているか確認してください。",
"checking_end": "チェックが完了しました",
"file_move": "ファイルを移動しました：{file}。",
"screenshots_sorted": "スクリーンショットファイルが整理されました",
"toast_move_file": "{file0}を「スクリーンショット」フォルダに移動しました。",
"toast_move_files": "{file0}など{num}個のファイルを「スクリーンショット」フォルダに移動しました。",
"process_dc_end": "rslrとssmの両方が停止し、子プロセスdesktop_controlが終了しました。",
"log_overflow": "ログが{num}件オーバーフローしました、削除しました。",
"close_window": "ウィンドウを閉じる：",
"same": "同じ",
"time_use": "使用時間",
"illegal_time": "不正な時間",
"colon": "：",
"or": "または",
"toast_illegal_time": "現在の時刻は、許可された起動時間{allowed_time_start}よりも前または{allowed_time_end}よりも後です。10秒後に自動的にシャットダウンされます。",
"auto_updated": "最新バージョンに更新されました",
"toast_auto_updated": "新しいバージョン{version}が有効になりました。更新ログを表示するにはクリックしてください。",
"error_illegal_package": "返された内容が正常ではありません",
"error_check_update":"更新チェック中にエラーが発生しました",
"retry":"、再試行中...{times}/3回",
"latest_version":"最新バージョンです！",
"no_download_url":"最新バージョンがあります：{latest_version}、しかしダウンロードリンクがありません。後でもう一度お試しください。",
"start_download":"最新バージョンがあります：{latest_version}、アップデートパッケージのダウンロードを開始します......",
"download_url":"ダウンロードリンク：",
"error_download":"アップデートパッケージのダウンロード中にエラーが発生しました",
"unpacking":"アップデートパッケージのダウンロードが完了しました、解凍を開始します......",
"add_self_starting":"解凍が完了しました、自動起動を追加しています...",
"prepared":"アップデートの準備が完了しました、再起動を待っています...",
"icon_missing":"警告：D:/tools/icon.icoが存在しません、通知のアイコンが正常に表示されません！",
"call_toast":"通知を送信しました\nタイトル：{title}\n内容：{content}\nコマンド：{command}",
"toast_title_default":"schoolpctool通知",
"error_toasting":"通知の送信中にエラーが発生しました",
"explorer_crashing":"おそらくexplorer.exeのクラッシュによるエラーです、このバージョンでは解決できません。",
"hour":"時間",
"minute":"分",
"second":"秒",
} 